ENV: PROD
PROD:
  DB: 
    HOST:
    PORT:
    USERNAME:
    PASS:
    SCHEMA:
  LOG:
    PATH: 
    NAME: 
    LEVEL: 20 #INFO
  SOCKET:
    HOST: 'localhost'
    PORT: 7497
  NORGATE:
    REMOTE_IP: '172.16.21.3'
    REMOTE_PORT: 38890
  SYMBOLS:
    YFINANCE_ALL_US_STOCK_SYMBOLS  : 'symbols/yfinance_us_symbols.txt'
    NORGATE_ALL_US_STOCK_SYMBOLS   : 'symbols/norgate_us_symbols.txt'
    DATABASE_UPDATE_SYMBOLS        : 'symbols/all_us_stocks_symbols.txt'
    DATABASE_UPDATE_ETF_SYMBOLS    : 'symbols/all_other_symbols.txt'
  MARKET_ASSET_TYPES:
    STOCK       : 'symbols/market_assets/stock.txt'
    FOREX       : 'symbols/market_assets/forex.txt'
    COMMODITY   : 'symbols/market_assets/commodity.txt'
    INDEX       : 'symbols/market_assets/index.txt'
    FUTURE      : 'symbols/market_assets/future.txt'
    OPTION      : 'symbols/market_assets/option.txt'
    CFD         : 'symbols/market_assets/cdf.txt'
    BOND        : 'symbols/market_assets/bond.txt'
    CRYPTO      : 'symbols/market_assets/crypto.txt'
    
  OPENAI:
    API_KEY: "================skjZKbSnjnc27======================"      # Replace APIKEY

TIMEFRAMES:
  - '5 mins'
  - '15 mins'
  - '30 mins'
  - '1 hour'
  - '4 hours'
  - '1 day'
  - '1 W'

DURATION_MAP:
  '5 mins'  : '5 D'
  '15 mins' : '14 D'
  '30 mins' : '26 D'
  '1 hour'  : '60 D'
  '4 hours' : '250 D'
  '1 day'   : '2 Y'
  '1 W'     : '10 Y'